import { Platform } from "react-native";
import colors from "../Utils/Colors";

export default {
  SafeareaViewCommanStyle: {
    backgroundColor: "white",
    height: "100%",
  },
  button: {
    backgroundColor: colors.blue,
    height: 50,
    justifyContent: "center",
    borderRadius: 5,
    marginVertical: 10,
    // marginTop: "85%",
    // marginHorizontal: 20,
  },
  buttonText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: "white",
  },
  header: {
    height: 60,
    backgroundColor: "black",
    justifyContent: "center",
  },
  TxtInputView: {
    flexDirection: "row",
    // borderWidth: 1.5,
    borderColor: "#B7B7B7",
    borderWidth: 0.6,
    // borderColor: "black",
    borderRadius: 5,
    padding: 10,
    marginTop: 15,
  },
  InputView: {
    height: 45,
    width: "100%",
    // backgroundColor: "white",
    borderWidth: 0.6,
    borderRadius: 5,
    borderColor: "#B7B7B7",
    // borderColor: "black",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 17,
    marginVertical: 10,
  },
  backgroundView: {
    height: "100%",
    width: "100%",
    backgroundColor: "black",
    opacity: 0.3,
  },
  modalView: {
    marginTop: "auto",
    backgroundColor: "white",
    alignSelf: "center",
    flexDirection: "column",
    padding: 15,
    height: "90%",
    width: "100%",
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    bottom: -20,
  },
  serachaddress_postal: {
    backgroundColor: "white",
    height: 70,
    width: "100%",
    marginVertical: 10,
    borderRadius: 8,
    borderWidth: 0.2,
    borderColor: "gray",
    paddingHorizontal: 15,
    justifyContent: "center",
  },
  Container: {
    flexDirection: "column",
    borderColor: "#F0F0F0",
    // backgroundColor: "green",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 8,
    marginRight: 8,
    width: "20%",
    borderWidth: 2,
  },
  ListView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: 80,
    width: 80,
  },
  headingText: {
    fontSize: 19,
    fontWeight: "500",
    color: "black",
    marginLeft: 3,
    marginTop: 10,
  },
  detailsTxt: {
    fontSize: 12,
    fontWeight: "400",
    color: "grey",
    marginLeft: 3,
    marginTop: 5,
  },
};
